fixed make file to download from google drive and removed graph from repo.

diff --git a/caffe/SSD_MobileNet/Makefile b/caffe/SSD_MobileNet/Makefile
--- a/caffe/SSD_MobileNet/Makefile
+++ b/caffe/SSD_MobileNet/Makefile
@@ -10,20 +10,17 @@ NCCHECK   = mvNCCheck
 # filenames for the graph files that we'll copy to this directory.
 SSD_MOBILENET_GRAPH_FILENAME = graph
 
-# The caffe model file is here, but can't do wget for file on
-# google drive.  Need to figure out how to download this from
-# script or makefile.  For now the compiled graph file
-# will be checked into the repository. The 'make compile' will be
-# tell you to go download it manually.
-#https://drive.google.com/open?id=0B3gersZ2cHIxRm5PMWRoTkdHdHc
-
 PROTOTXT_FILENAME= MobileNetSSD_deploy.prototxt
-#PROTOTXT_FILENAME= mobile_net_ssd.prototxt
 
 GET_PROTOTXT = wget -P . -O ${PROTOTXT_FILENAME} https://raw.githubusercontent.com/chuanqi305/MobileNet-SSD/master/${PROTOTXT_FILENAME}
 
 CAFFEMODEL_FILENAME = MobileNetSSD_deploy.caffemodel
-GET_CAFFEMODEL = wget -P . -N http://blah.com/${CAFFEMODEL_FILENAME}
+
+# The caffe model file is at this google drive link.
+# https://drive.google.com/open?id=0B3gersZ2cHIxRm5PMWRoTkdHdHc
+#
+# This command does a wget for a google drive document ID 
+GET_CAFFEMODEL = touch /tmp/cookies.txt; wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=0B3gersZ2cHIxRm5PMWRoTkdHdHc' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=0B3gersZ2cHIxRm5PMWRoTkdHdHc" -O ${CAFFEMODEL_FILENAME} && rm -rf /tmp/cookies.txt
 
 
 .PHONY: all
@@ -54,23 +51,45 @@ prototxt: prereqs
 		fi ; \
 	fi  
 
-.PHONY: caffemodel
-caffemodel: 
+.PHONY: old_caffemodel
+old_caffemodel: 
 	@echo "\nmaking caffemodel"
 	@if [ -e ${CAFFEMODEL_FILENAME} ] ; \
 	then \
 		echo "caffemodel file already exists"; \
 	else \
-	    echo "-----------------"; \
-	    echo "The caffe model file is at the google drive URL below."; \
-	    echo "For now the compiled graph file is included in this"; \
-	    echo "project directory so its not required to download the model."; \
-	    echo "or even compile it.  Its already there."; \
-	    echo "If you want to compile the model yourself please download it here:"; \
-	    echo ""; \
-	    echo "https://drive.google.com/open?id=0B3gersZ2cHIxRm5PMWRoTkdHdHc"; \
-	    echo "-----------------"; \
-    fi
+		echo "-----------------"; \
+		echo "The caffe model file is at the google drive URL below."; \
+		echo "For now the compiled graph file is included in this"; \
+		echo "project directory so its not required to download the model."; \
+		echo "or even compile it.  Its already there."; \
+		echo "If you want to compile the model yourself please download it here:"; \
+		echo ""; \
+		echo "https://drive.google.com/open?id=0B3gersZ2cHIxRm5PMWRoTkdHdHc"; \
+		echo "-----------------"; \
+		echo "Attempting to download Caffe Model from google drive"; \
+	fi
+
+.PHONY: caffemodel
+caffemodel: 
+	@echo "\nmaking caffemodel"; \
+	if [ -e ${CAFFEMODEL_FILENAME} ] ; \
+	then \
+		echo "caffemodel already exists, skipping download."; \
+	else \
+		echo ""; \
+		echo "Attempting download of caffemodel file from this url: "; \
+		echo "https://drive.google.com/open?id=0B3gersZ2cHIxRm5PMWRoTkdHdHc"; \
+		echo ""; \
+		${GET_CAFFEMODEL}; \
+		if ! [ -e ${CAFFEMODEL_FILENAME} ] ; \
+		then \
+			echo "caffemodel download failed from url: "; \
+			echo "https://drive.google.com/open?id=0B3gersZ2cHIxRm5PMWRoTkdHdHc"; \
+			echo "Please download it manually or check internet connection and retry."; \
+		fi; \
+	fi
+
 
 # If the model becomes available for download via wget do it like this:
 #@echo "Downloading caffemodel file"; \
@@ -83,21 +102,9 @@ caffemodel:
 
 
 .PHONY: compile
-compile: 
+compile: caffemodel prototxt
 	@echo "\nmaking compile"
-	@echo "-----------------"
-	@echo "The compiled graph file for the network is included in the"
-	@echo "project directory for now so there is no need to compile it."
-	@echo "If you do want to compile it yourself you will need to first"
-	@echo "download the model from the URL below and then run the command below."
-	@echo ""
-	@echo "URL for caffe model is:"
-	@echo "https://drive.google.com/open?id=0B3gersZ2cHIxRm5PMWRoTkdHdHc"
-	@echo ""
-	@echo "Command to compile the model is: "
-	@echo "${NCCOMPILE} -w ${CAFFEMODEL_FILENAME} -s 12 ${PROTOTXT_FILENAME}"
-	@echo "-----------------"
-
+	${NCCOMPILE} -w ${CAFFEMODEL_FILENAME} -s 12 ${PROTOTXT_FILENAME}
 
 .PHONY: run_py
 run_py: all
@@ -119,6 +126,7 @@ help:
 clean: 
 	@echo "\nmaking clean"
 	rm -f ./${PROTOTXT_FILENAME}
-	# rm -f ${SSD_MOBILENET_GRAPH_FILENAME}
+	rm -f ${SSD_MOBILENET_GRAPH_FILENAME}
+	rm -f ${CAFFEMODEL_FILENAME}
 
 
