openvino_2019_r2 initial checkin

diff --git a/caffe/AlexNet/Makefile b/caffe/AlexNet/Makefile
--- a/caffe/AlexNet/Makefile
+++ b/caffe/AlexNet/Makefile
@@ -1,139 +1,117 @@
+NCCOMPILE = mo.py
 
-ifneq ($(findstring movidius, $(PYTHONPATH)), movidius)
-	export PYTHONPATH:=/opt/movidius/caffe/python:/opt/movidius/mvnc/python:$(PYTHONPATH)
-endif
+GREEN = '\033[1;32m'
+YELLOW = '\033[1;33m'
+RED = '\033[1;31m'
+NOCOLOR = '\033[0m'
 
-NCCOMPILE = mvNCCompile
-NCPROFILE = mvNCProfile
-NCCHECK   = mvNCCheck
+SIMPLE_CLASSIFIER_CPP_RELATIVE_DIR = ../../apps/simple_classifier_cpp
+SIMPLE_CLASSIFIER_PY_RELATIVE_DIR = ../../apps/simple_classifier_py
 
-PROTOTXT_FILENAME= deploy.prototxt
-GET_PROTOTXT = wget -P . https://raw.githubusercontent.com/BVLC/caffe/master/models/bvlc_alexnet/${PROTOTXT_FILENAME}
+TEST_IMAGE_RELATIVE_DIR = ../../data/images
+LABELS_RELATIVE_DIR = ../../data/ilsvrc12
+MODEL_RELATIVE_DIR = ../../caffe/AlexNet
 
-CAFFEMODEL_FILENAME = bvlc_alexnet.caffemodel
-GET_CAFFEMODEL = wget -P . -N http://dl.caffe.berkeleyvision.org/${CAFFEMODEL_FILENAME}
+TEST_IMAGE_FILENAME = nps_electric_guitar.png
+LABELS_FILENAME = synset_labels.txt
 
+ZOO_RELATIVE_DIR = ../../omz
+MODEL_DOWNLOADER_DIR = open_model_zoo/tools/downloader
+MODEL_DOWNLOADER_FILENAME = downloader.py
+ALEXNET_MODEL_ZOO_DIR = classification/alexnet/caffe
+
+MODEL_FILE_NAME_BASE = alexnet
+MEAN_VALUES = [104,117,123]
 
 .PHONY: all
-all: compile cpp
+all: deps data compile_model compile_cpp
 
-.PHONY: prereqs
-prereqs:
-	@echo "\nmaking prereqs"
-	(cd ../../data/ilsvrc12; make)
-	@sed -i 's/\r//' run.py
-	chmod +x run.py
 
-.PHONY: prototxt
-prototxt: prereqs
-	@echo "\nmaking prototxt"
-	@if [ -e ${PROTOTXT_FILENAME} ] ; \
+.PHONY: deps
+deps: download_model_files
+	@echo $(YELLOW)"\nAlexNet: Making dependencies..."$(NOCOLOR)
+	
+	
+.PHONY: data
+data:
+	@echo $(YELLOW)"\nAlexNet: Downloading required data..."$(NOCOLOR)
+	(cd ../../data/ilsvrc12; make all;)
+
+
+.PHONY: model_zoo
+model_zoo:
+	@echo $(YELLOW)"\nAlexNet: Making model zoo..."$(NOCOLOR)
+	(cd ${ZOO_RELATIVE_DIR}; make all;)
+
+
+.PHONY: download_model_files
+download_model_files: model_zoo
+	@echo $(YELLOW)"\nAlexNet: Checking zoo model files..."$(NOCOLOR)
+	@if [ -e ${ZOO_RELATIVE_DIR}/${MODEL_DOWNLOADER_DIR}/${ALEXNET_MODEL_ZOO_DIR}/${MODEL_FILE_NAME_BASE}.caffemodel ] || [ -e ${ZOO_RELATIVE_DIR}/${MODEL_DOWNLOADER_DIR}/${ALEXNET_MODEL_ZOO_DIR}/${MODEL_FILE_NAME_BASE}.prototxt ] ;\
 	then \
-		echo "Prototxt file already exists"; \
+		echo " - Model files already exists." ; \
 	else \
-		echo "Downloading Prototxt file"; \
-		${GET_PROTOTXT}; \
-		if [ -e ${PROTOTXT_FILENAME} ] ; \
-		then \
-			echo "Adding input shape to prototxt file."; \
-			awk 'NR <2 {print}' < ${PROTOTXT_FILENAME} > temp; cat input_shape.prototxt >> temp; awk 'NR > 7 {print}' < ${PROTOTXT_FILENAME} >> temp; mv temp ${PROTOTXT_FILENAME}; \
-		else \
-			echo "***\nError - Could not download prototxt file. Check network and proxy settings \n***\n"; \
-			exit 1; \
-		fi ; \
-	fi  
+		echo " - Model files do not exist. Using Model downloader to download the model..." ; \
+		(cd ${ZOO_RELATIVE_DIR}/${MODEL_DOWNLOADER_DIR}; python3 ${MODEL_DOWNLOADER_FILENAME} --name ${MODEL_FILE_NAME_BASE};); \
+	fi
 
-.PHONY: caffemodel
-caffemodel: 
-	@echo "\nmaking caffemodel"
-	@if [ -e ${CAFFEMODEL_FILENAME} ] ; \
+
+.PHONY: compile_model
+compile_model: download_model_files
+	@echo $(YELLOW)"\nAlexNet: Compiling model to IR..."$(NOCOLOR)
+	@if [ -e ${MODEL_FILE_NAME_BASE}.xml ] && [ -e ${MODEL_FILE_NAME_BASE}.bin ]; \
 	then \
-		echo "caffemodel file already exists"; \
+		echo " - IR files already exist. Skipping compile step."; \
 	else \
-		echo "Downloading caffemodel file"; \
-		${GET_CAFFEMODEL}; \
-		if ! [ -e ${CAFFEMODEL_FILENAME} ] ; \
-		then \
-			echo "***\nError - Could not download caffemodel file. Check network and proxy settings \n***\n"; \
-			exit 1; \
-		fi ; \
-	fi  
+		${NCCOMPILE} --data_type=FP16 --input_model=${ZOO_RELATIVE_DIR}/${MODEL_DOWNLOADER_DIR}/${ALEXNET_MODEL_ZOO_DIR}/${MODEL_FILE_NAME_BASE}.caffemodel --input_proto=${ZOO_RELATIVE_DIR}/${MODEL_DOWNLOADER_DIR}/${ALEXNET_MODEL_ZOO_DIR}/${MODEL_FILE_NAME_BASE}.prototxt --mean_values=${MEAN_VALUES} || (echo $(RED)"Make sure your paths are correct and the OpenVINO environment variables are set using the "$(YELLOW)"setupvars.sh"$(RED)" script found in <your OpenVINO install location>/bin/ folder."$(NOCOLOR);  exit 1;); \
+	fi 
 
-.PHONY: profile
-profile: prototxt
-	@echo "\nmaking profile"
-	${NCPROFILE} ${PROTOTXT_FILENAME} -s 12
-
-.PHONY: browse_profile
-browse_profile: profile
-	@echo "\nmaking browse_profile"
-	@if [ -e output_report.html ] ; \
-	then \
-		firefox output_report.html & \
-	else \
-		@echo "***\nError - output_report.html not found" ; \
-	fi ; 
-
-.PHONY: compile
-compile: prototxt caffemodel
-	@echo "\nmaking compile"
-	${NCCOMPILE} -w ${CAFFEMODEL_FILENAME} -s 12 ${PROTOTXT_FILENAME}
-
-.PHONY: check
-check: prototxt caffemodel
-	@echo "\nmaking check"
-#-${NCCHECK} -w ${CAFFEMODEL_FILENAME} -i ../../data/images/cat.jpg -s 12 -id 281 ${PROTOTXT_FILENAME} -S 255 -M ../../data/ilsvrc12/ilsvrc_2012_mean.npy
-	-${NCCHECK} -w ${CAFFEMODEL_FILENAME} -i ../../data/images/cat.jpg -s 12 -id 281 ${PROTOTXT_FILENAME} -M 110 -S 255
 
 .PHONY: run
-run: compile
-	@echo "\nmaking run"
-	./run.py
+run: run_py
 
-.PHONY: run_py
-run_py: compile
-	@echo "\nmaking run_py"
-	./run.py
 
-.PHONY:	cpp
-cpp: cpp/run.cpp 
-	@echo "\nmaking cpp"
-	g++ cpp/run.cpp -o cpp/run_cpp -lmvnc
+.PHONY:	compile_cpp
+compile_cpp:  
+	@echo $(YELLOW)"\nAlexNet: Compiling C++ sample..."$(NOCOLOR)
+	(cd ${SIMPLE_CLASSIFIER_CPP_RELATIVE_DIR}; make compile_cpp; cd -)
+
 
 .PHONY: run_cpp
-run_cpp: compile cpp
-	@echo "\nmaking run_cpp"
-	cd cpp; ./run_cpp; cd ..
+run_cpp: install-reqs deps data compile_cpp compile_model
+	@echo $(YELLOW)"\nAlexNet: Running C++ sample..."$(NOCOLOR)
+	${SIMPLE_CLASSIFIER_CPP_RELATIVE_DIR}/build/simple_classifier_cpp ${MODEL_FILE_NAME_BASE}.xml ${TEST_IMAGE_RELATIVE_DIR}/${TEST_IMAGE_FILENAME} ${LABELS_RELATIVE_DIR}/${LABELS_FILENAME};
+
+
+.PHONY: install-reqs
+install-reqs: 
+	@echo $(YELLOW)"\nAlexNet: Checking application requirements...\n"$(NOCOLOR)
+	@echo "No requirements needed."
+	
+
+.PHONY: run_py
+run_py: install-reqs deps data compile_model
+	@echo $(YELLOW)"\nAlexNet: Running Python sample..."$(NOCOLOR)
+	python3 ${SIMPLE_CLASSIFIER_PY_RELATIVE_DIR}/run.py --ir=${MODEL_FILE_NAME_BASE}.xml --image=${TEST_IMAGE_RELATIVE_DIR}/${TEST_IMAGE_FILENAME} --labels=${LABELS_RELATIVE_DIR}/${LABELS_FILENAME} --top=5; 
+
 
 .PHONY: help
 help:
-	@echo "possible make targets: ";
-	@echo "  make help - shows this message";
-	@echo "  make all - makes the following: prototxt, profile, compile, check, cpp, run_py, run_cpp";
-	@echo "  make prototxt - downloads and adds input shape to Caffe prototxt file";
-	@echo "  make caffemodel - downloads the caffemodel for the network"
-	@echo "  make compile - runs SDK compiler tool to compile the NCS graph file for the network";
-	@echo "  make check - runs SDK checker tool to verify an NCS graph file";
-	@echo "  make profile - runs the SDK profiler tool to profile the network creating output_report.html";
-	@echo "  make browse_profile - runs the SDK profiler tool and brings up report in browser.";
-	@echo "  make cpp - builds the run_cpp executable example";
-	@echo "  make run_cpp - runs the run_cpp executable example program";
-	@echo "  make run_py - runs the run.py python example program:";
-	@echo "  make clean - removes all created content"
+	@echo "\nPossible make targets: ";
+	@echo $(YELLOW)"  make run "$(NOCOLOR)"- Runs the Python example.";
+	@echo $(YELLOW)"  make run_py "$(NOCOLOR)"- Runs the Python example.";
+	@echo $(YELLOW)"  make run_cpp "$(NOCOLOR)"- Runs the C++ example.";
+	@echo $(YELLOW)"  make help "$(NOCOLOR)"- Shows this message.";
+	@echo $(YELLOW)"  make all "$(NOCOLOR)"- Makes everything needed to run, but doesn't run.";
+	@echo $(YELLOW)"  make compile_model "$(NOCOLOR)"- Compiles the model to an IR format.";
+	@echo $(YELLOW)"  make compile_cpp "$(NOCOLOR)"- Builds the C++ example.";
+	@echo $(YELLOW)"  make data "$(NOCOLOR)"- Downloads the required data.";
+	@echo $(YELLOW)"  make deps "$(NOCOLOR)"- Makes dependencies for project, downloads and prepares model etc.";
+	@echo $(YELLOW)"  make clean "$(NOCOLOR)"- Removes all temporary files that are created by the Makefile.\n";
+	
 
-clean_caffe_model:
-	@echo "\nmaking clean_caffe_model"
-	rm -f ${PROTOTXT_FILENAME}
-	rm -f ${CAFFEMODEL_FILENAME}
-
-clean: clean_caffe_model
-	@echo "\nmaking clean"
-	rm -f graph
-	rm -f output.gv
-	rm -f output.gv.svg
-	rm -f output_report.html
-	rm -f output_expected.npy
-	rm -f zero_weights.caffemodel
-	rm -f output_result.npy
-	rm -f output_val.csv
-	rm -f cpp/run_cpp
+clean: 
+	@echo $(YELLOW)"\nAlexNet: Cleaning up files..."$(NOCOLOR)
+	rm -f ${MODEL_FILE_NAME_BASE}.bin
+	rm -f ${MODEL_FILE_NAME_BASE}.xml
+	rm -f ${MODEL_FILE_NAME_BASE}.mapping
diff --git a/tensorflow/mnist/Makefile b/tensorflow/mnist/Makefile
--- a/tensorflow/mnist/Makefile
+++ b/tensorflow/mnist/Makefile
@@ -1,11 +1,18 @@
+NCCOMPILE = mo.py
 
-NCCOMPILE = mvNCCompile
-NCPROFILE = mvNCProfile
-NCCHECK   = mvNCCheck
-
+YELLOW='\033[1;33m'
+NOCOLOR='\033[0m'
+RED = '\033[1;31m'
 
 NETWORK_SCRIPT_FILENAME= mnist_deep.py
 GET_NETWORK_SCRIPT = wget -P . https://raw.githubusercontent.com/tensorflow/tensorflow/r1.4/tensorflow/examples/tutorials/mnist/${NETWORK_SCRIPT_FILENAME}
+PATCH_FOR_NCS_FILENAME = orig_2_ncs.patch
+PATCH_FOR_INFERENCE_FILENAME = ncs_2_inference.patch
+
+MNIST_NCS_FILENAME = mnist_deep_mod.py
+MNIST_INFERENCE_FILENAME = mnist_deep_inference.py
+
+GRAPH_FILENAME_BASE = mnist
 
 MODEL_DATA_FILENAME = mnist_model.data-00000-of-00001
 MODEL_INDEX_FILENAME = mnist_model.index
@@ -15,48 +22,35 @@ MODEL_INFERENCE_DATA_FILENAME = mnist_inference.data-00000-of-00001
 MODEL_INFERENCE_INDEX_FILENAME = mnist_inference.index
 MODEL_INFERENCE_META_FILENAME = mnist_inference.meta
 
-
-PATCH_FOR_NCS_FILENAME = orig_2_ncs.patch
-PATCH_FOR_INFERENCE_FILENAME = ncs_2_inference.patch
-
-MNIST_NCS_FILENAME = mnist_deep_mod.py
-MNIST_INFERENCE_FILENAME = mnist_deep_inference.py
-
 GET_MODEL_DATA = wget -c --no-cache -P . https://raw.githubusercontent.com/nealvis/neural_nets/master/tensorflow/mnist/${MODEL_INFERENCE_DATA_FILENAME}
 GET_MODEL_INDEX = wget -c --no-cache -P . https://raw.githubusercontent.com/nealvis/neural_nets/master/tensorflow/mnist/${MODEL_INFERENCE_INDEX_FILENAME}
 GET_MODEL_META =  wget -c --no-cache -P . https://raw.githubusercontent.com/nealvis/neural_nets/master/tensorflow/mnist/${MODEL_INFERENCE_META_FILENAME}
 
-GRAPH_FILENAME = mnist_inference.graph
+GRAPH_FILENAME_BASE = mnist_inference
+MODEL_RELATIVE_DIR = .
+
+RUN_PY_RELATIVE_DIR = mnist.py
+TEST_IMAGE_RELATIVE_DIR = ../../data/digit_images
+TEST_IMAGE_FILENAME = one.png
+INPUT_SHAPE = [1,784]
 
 .PHONY: all
-all: deps compile
+all: deps data compile_model
+
 
 .PHONY: deps
-deps: model
-	@echo "\nmaking deps"
-
-.PHONY: network_code
-network_code:
-	@echo "\making network_code"
-	@if [ -e ${NETWORK_SCRIPT_FILENAME} ] ; \
-	then \
-		echo "network script ${NETWORK_SCRIPT_FILENAME} already exists, skipping download"; \
-	else \
-		echo "Downloading ${NETWORK_SCRIPT_FILENAME} file"; \
-		${GET_NETWORK_SCRIPT}; \
-		if [ -e ${NETWORK_SCRIPT_FILENAME} ] ; \
-		then \
-			echo "download ${NETWORK_SCRIPT_FILENAME} done."; \
-		else \
-			echo "***\nError - Could not download ${NETWORK_SCRIPT_FILENAME}. Check network and proxy settings \n***\n"; \
-			exit 1; \
-		fi ; \
-	fi
+deps: get_model
+	@echo $(YELLOW)"\nMnist: Making dependencies..."$(NOCOLOR)
 
 
-.PHONY: model
-model:
-	@echo "\nmaking model"
+.PHONY: data
+data:
+	@echo $(YELLOW)"\nMnist: Downloading required data - No data needed."$(NOCOLOR)
+
+
+.PHONY: get_model
+get_model:
+	@echo $(YELLOW)"\nMnist: Downloading model files..."$(NOCOLOR)
 	@if [ -e ${MODEL_INFERENCE_DATA_FILENAME} ] ; \
 	then \
 		echo "model file ${MODEL_INFERENCE_DATA_FILENAME} already exists, skipping download"; \
@@ -99,11 +93,11 @@ model:
 			exit 1; \
 		fi ; \
 	fi
-
-
+	
+	
 .PHONY: train
 train:
-	@echo "\nmaking train";
+	@echo $(YELLOW) "\nMnist: Training model..." $(NOCOLOR);
 	@echo "\nTo train the network the following steps will be taken:";
 	@echo "  - Download the TensorFlow mnist_deep.py example";
 	@echo "  - Modify the mnist_deep.py -> mnist_deep_mod.py for NCS compatibility";
@@ -114,15 +108,15 @@ train:
 	@echo "  - modify mnist_deep_mod.py -> mnist_deep_inference.py for inference only version";
 	@echo "    of the network (no training code)."
 	@echo "  - run mnist_deep_inference.py to read the saved network and write an inference";
-	@echo "    only version of the network that the NCSDK can compile in these files:";
+	@echo "    only version of the network that the OpenVINO Model Optimizer can compile in these files:";
 	@echo "      ${MODEL_INFERENCE_DATA_FILENAME}";
 	@echo "      ${MODEL_INFERENCE_INDEX_FILENAME}";
 	@echo "      ${MODEL_INFERENCE_META_FILENAME}";
 	@echo "  "
-	@echo "After complete, you will be able to compile the network you just trained with:"
-	@echo "make compile"
+	@echo "After complete, you will be able to compile the network you just trained with:";
+	@echo "make compile_model";
 	@echo ""
-	@read -p"Press ENTER to continue the steps above (this will take about 20 min) or Ctrl-C to cancel" variable_nps;echo;
+	@read -p"Press ENTER to continue the steps above (this will take about 20 min) or Ctrl-C to cancel" variable_nps; echo;
 
 	@if [ -e ${NETWORK_SCRIPT_FILENAME} ] ; \
 	then \
@@ -139,89 +133,73 @@ train:
 		fi ; \
 	fi ;
 
-
-	@echo "patching example for NCSDK";
+	@echo "patching example for the OpenVINO Toolkit";
 	patch ${NETWORK_SCRIPT_FILENAME} -i ${PATCH_FOR_NCS_FILENAME} -o ${MNIST_NCS_FILENAME};
 	patch ${MNIST_NCS_FILENAME} -i ${PATCH_FOR_INFERENCE_FILENAME} -o ${MNIST_INFERENCE_FILENAME};
 	@echo "Running patched code to start training";
 	python3 ./${MNIST_NCS_FILENAME}
-	@echo "Running code to save for NCSDK";
+	@echo "Running code to save for the OpenVINO Toolkit";
 	python3 ./${MNIST_INFERENCE_FILENAME}
+	@echo $(YELLOW)"\nMnist model training complete."$(NOCOLOR)
+	@echo "Model name: "${MODEL_INFERENCE_META_FILENAME} 
+	@echo $(NOCOLOR)"\nRun the command "$(YELLOW)"make compile_model"$(NOCOLOR)" to compile your model or "$(YELLOW)"make run"$(NOCOLOR)" to run the sample with your trained model.\n"
 
 
-.PHONY: profile
-profile: model
-	@echo "\nmaking profile"
-	@echo "No profile for this network yet"
-
-.PHONY: browse_profile
-browse_profile: profile
-	@echo "\nmaking browse_profile"
-	@if [ -e output_report.html ] ; \
+.PHONY: compile_model
+compile_model: get_model
+	@echo $(YELLOW)"\nMnist: Compiling model to IR..."$(NOCOLOR)
+	@if [ -e ${GRAPH_FILENAME_BASE}.xml ] ; \
 	then \
-		firefox output_report.html & \
+		echo "compiled model file already exists, skipping compile."; \
 	else \
-		@echo "***\nError - output_report.html not found" ; \
-	fi ; 
-
-
-.PHONY: compile
-compile: model
-	@echo "\nmaking compile"
-	@if [ -e ${GRAPH_FILENAME} ] ; \
-	then \
-		echo "graph file ${GRAPH_FILENAME} already exists, skipping compile"; \
-	else \
-		echo "Compiling to create ${GRAPH_FILENAME}"; \
-		${NCCOMPILE} ${MODEL_INFERENCE_META_FILENAME} -w mnist_inference -s 12 -in input -on output -o ${GRAPH_FILENAME}; \
-		if [ -e ${GRAPH_FILENAME} ] ; \
-		then \
-			echo "compile done, created ${GRAPH_FILENAME}."; \
-		else \
-			echo "***\nError - Could not compile, not able to create ${GRAPH_FILENAME} \n***\n"; \
-			exit 1; \
-		fi ; \
+		${NCCOMPILE} --data_type=FP16 --input_meta_graph=${MODEL_INFERENCE_META_FILENAME} --input_shape=${INPUT_SHAPE} || (echo $(RED)"Make sure to set the OpenVINO environment variables using the "$(YELLOW)"setupvars.sh"$(RED)" script found in <your OpenVINO install location>/bin/ folder."$(NOCOLOR);  exit 1;); \
 	fi
 
 
-.PHONY: check
-check: model
-	@echo "\nmaking check"
-	@echo "\No check for this network yet."
-
-
+.PHONY: install-reqs
+install-reqs: 
+	@echo $(YELLOW)"\nMnist: Checking application requirements...\n"$(NOCOLOR)
+	@echo "No requirements needed."
+	
+	
 .PHONY: run
-run: deps compile
-	@echo "\nmaking run"
-	python3 ./run.py
+run: run_py
+
+
+.PHONY: run_py
+run_py: install-reqs deps data compile_model
+	@echo $(YELLOW) "\nMnist: Running Python sample..." $(NOCOLOR)
+	python3 $(RUN_PY_RELATIVE_DIR) --ir=${MODEL_RELATIVE_DIR}/${GRAPH_FILENAME_BASE}.xml --image=${TEST_IMAGE_RELATIVE_DIR}/${TEST_IMAGE_FILENAME} --labels=categories.txt
+
 
 .PHONY: help
 help:
-	@echo "possible make targets: ";
-	@echo "  make help - shows this message";
-	@echo "  make all - makes the following: deps, compile";
-	@echo "  make browse_profile - (TBD) runs the SDK profiler tool and brings up report in browser.";
-	@echo "  make check - (TBD) runs SDK checker tool to verify an NCS graph file";
-	@echo "  make clean - removes all created content"
-	@echo "  make compile - runs SDK compiler tool to compile the graph file for the network";
-	@echo "  make deps - downloads and prepares the trained network";
-	@echo "  make profile - (TBD) runs the SDK profiler tool to profile the network creating output_report.html";
-	@echo "  make run - runs the run.py python example program";
-	@echo "  make train - creates NCSDK compatible version of TF network and trains it.";
-
+	@echo "\nPossible make targets"
+	@echo $(YELLOW)"  make help " $(NOCOLOR) "- Shows this message.";
+	@echo $(YELLOW)"  make run " $(NOCOLOR) "- Runs the Python example.";
+	@echo $(YELLOW)"  make run_py " $(NOCOLOR) "- Runs the Python example.";
+	@echo $(YELLOW)"  make all " $(NOCOLOR) "- Makes everything needed to run, but doesn't run the sample.";
+	@echo $(YELLOW)"  make compile_model " $(NOCOLOR) "- Runs model compiler for the network.";
+	@echo $(YELLOW)"  make model " $(NOCOLOR) "- Downloads the model files.";
+	@echo $(YELLOW)"  make data " $(NOCOLOR) "- Downloads required data.";
+	@echo $(YELLOW)"  make deps " $(NOCOLOR) "- Makes dependencies for project, prepares model etc.";
+	@echo $(YELLOW)"  make clean " $(NOCOLOR) "- Removes all the temporary files that are created by the Makefile.";
+	@echo $(YELLOW)"  make train " $(NOCOLOR) "- Train a mnist model.";
 
 clean: clean
-	@echo "\nmaking clean"
-	rm -f ${GRAPH_FILENAME}
+	@echo $(YELLOW)"\nMnist: Cleaning up files..."$(NOCOLOR)
+	rm -f ${GRAPH_FILENAME_BASE}.bin
+	rm -f ${GRAPH_FILENAME_BASE}.mapping.json
+	rm -f ${GRAPH_FILENAME_BASE}.mapping
+	rm -f ${GRAPH_FILENAME_BASE}.xml
 	rm -f ${MODEL_INFERENCE_META_FILENAME}
 	rm -f ${MODEL_INFERENCE_INDEX_FILENAME}
 	rm -f ${MODEL_INFERENCE_DATA_FILENAME}
-	rm -f ${NETWORK_SCRIPT_FILENAME}
-	rm -f ${MODEL_META_FILENAME}
-	rm -f ${MODEL_INDEX_FILENAME}
-	rm -f ${MODEL_DATA_FILENAME}
-	rm -f checkpoint
 	rm -f ${MNIST_NCS_FILENAME}
 	rm -f ${MNIST_INFERENCE_FILENAME}
-	rm -f output_expected.npy
-
+	rm -f ${NETWORK_SCRIPT_FILENAME}
+	rm -f ${MODEL_DATA_FILENAME}
+	rm -f ${MODEL_INDEX_FILENAME}
+	rm -f ${MODEL_META_FILENAME}
+	rm -f checkpoint
+	
