Edits to make file: clean, get_model, compile_model

diff --git a/tensorflow/SSD_Inception_V2/Makefile b/tensorflow/SSD_Inception_V2/Makefile
--- a/tensorflow/SSD_Inception_V2/Makefile
+++ b/tensorflow/SSD_Inception_V2/Makefile
@@ -6,37 +6,40 @@ RED = '\033[1;31m'
 
 NETWORK_SCRIPT_FILENAME= mnist_deep.py
 GET_NETWORK_SCRIPT = wget -P . https://raw.githubusercontent.com/tensorflow/tensorflow/r1.4/tensorflow/examples/tutorials/mnist/${NETWORK_SCRIPT_FILENAME}
-PATCH_FOR_NCS_FILENAME = orig_2_ncs.patch
-PATCH_FOR_INFERENCE_FILENAME = ncs_2_inference.patch
 
 MNIST_NCS_FILENAME = mnist_deep_mod.py
 MNIST_INFERENCE_FILENAME = mnist_deep_inference.py
 
+
 GRAPH_FILENAME_BASE = ssd_inception_v2
+GRAPH_DIR_FP32 = ssd_inception_v2_mo_fp32
+GRAPH_DIR_FP16 = ssd_inception_v2_mo_fp16
+GRAPH_FILENAME_BASE_IN_DIR_FP32 = ssd_inception_v2_mo_fp32/frozen_inference_graph.xml
+GRAPH_FILENAME_BASE_IN_DIR_FP16 = ssd_inception_v2_mo_fp16/frozen_inference_graph.xml
+MO_INPUT_GRAPH_ARG = --input_model tensorflow_model/frozen_inference_graph.pb
+MO_INPUT_PIPELINE = --tensorflow_object_detection_api_pipeline_config tensorflow_model/pipeline.config
+MO_INPUT_CUSTOM_OPS = --tensorflow_use_custom_operations_config ssd_v2_support_inception.json
+MO_OUTPUT_DIR_FP32 = --output_dir ssd_inception_v2_mo_fp32
+MO_OUTPUT_DIR_FP16 = --output_dir ssd_inception_v2_mo_fp16
 
-MODEL_DATA_FILENAME = mnist_model.data-00000-of-00001
-MODEL_INDEX_FILENAME = mnist_model.index
-MODEL_META_FILENAME = mnist_model.meta
+MODEL_DIR = tensorflow_model
+MODEL_PIPELINE_CONFIG = tensorflow_model/pipeline.config
+MODEL_PB = tensorflow_model/frozen_inference_graph.pb
+MODEL_INFERENCE_PIPELINE_CONFIG = pipeline.config
+MODEL_INFERENCE_PB = frozen_inference_graph.pb
 
-MODEL_INFERENCE_DATA_FILENAME = mnist_inference.data-00000-of-00001
-MODEL_INFERENCE_INDEX_FILENAME = mnist_inference.index
-MODEL_INFERENCE_META_FILENAME = mnist_inference.meta
-
-GET_MODEL_DATA = wget -c --no-cache -P . https://raw.githubusercontent.com/nealvis/neural_nets/master/tensorflow/mnist/${MODEL_INFERENCE_DATA_FILENAME}
-GET_MODEL_INDEX = wget -c --no-cache -P . https://raw.githubusercontent.com/nealvis/neural_nets/master/tensorflow/mnist/${MODEL_INFERENCE_INDEX_FILENAME}
-GET_MODEL_META =  wget -c --no-cache -P . https://raw.githubusercontent.com/nealvis/neural_nets/master/tensorflow/mnist/${MODEL_INFERENCE_META_FILENAME}
+GET_MODEL_PIPELINE = wget -c --no-cache -P ./tensorflow_model https://raw.githubusercontent.com/fcr3/gesture_detection/master/tensorflow_model/${MODEL_INFERENCE_PIPELINE_CONFIG}
+GET_MODEL_PB = python3 download_weights.py
 
 GRAPH_FILENAME_BASE = mnist_inference
 MODEL_RELATIVE_DIR = .
 
 RUN_PY_RELATIVE_DIR = mnist.py
 TEST_IMAGE_RELATIVE_DIR = ../../data/digit_images
-TEST_IMAGE_FILENAME = one.png
-INPUT_SHAPE = [1,784]
+TEST_IMAGE_FILENAME = gesture.jpg
 
 .PHONY: all
 all: deps data compile_model
-
 
 .PHONY: deps
 deps: get_model
@@ -50,46 +53,32 @@ data:
 
 .PHONY: get_model
 get_model:
-	@echo $(YELLOW)"\nMnist: Downloading model files..."$(NOCOLOR)
-	@if [ -e ${MODEL_INFERENCE_DATA_FILENAME} ] ; \
+	@echo $(YELLOW)"\nSSD Inception V2: Downloading model files..."$(NOCOLOR)
+	@if [ -e ${MODEL_PIPELINE_CONFIG} ] ; \
 	then \
-		echo "model file ${MODEL_INFERENCE_DATA_FILENAME} already exists, skipping download"; \
+		echo "model file ${MODEL_PIPELINE_CONFIG} already exists, skipping download"; \
 	else \
-		echo "Downloading ${MODEL_INFERENCE_DATA_FILENAME} file"; \
-		${GET_MODEL_DATA}; \
-		if [ -e ${MODEL_INFERENCE_DATA_FILENAME} ] ; \
+		echo "Downloading ${MODEL_INFERENCE_PIPELINE_CONFIG} file"; \
+		${GET_MODEL_PIPELINE}; \
+		if [ -e ${MODEL_PIPELINE_CONFIG} ] ; \
 		then \
-			echo "download ${MODEL_INFERENCE_DATA_FILENAME} done."; \
+			echo "download ${MODEL_INFERENCE_PIPELINE_CONFIG} done. Downloaded to /tensorflow_model."; \
 		else \
-			echo "***\nError - Could not download ${MODEL_INFERENCE_DATA_FILENAME}. Check network and proxy settings \n***\n"; \
+			echo "***\nError - Could not download ${MODEL_INFERENCE_PIPELINE_CONFIG}. Check network and proxy settings \n***\n"; \
 			exit 1; \
 		fi ; \
 	fi
-	@if [ -e ${MODEL_INFERENCE_META_FILENAME} ] ; \
+	@if [ -e ${MODEL_PB} ] ; \
 	then \
-		echo "model file ${MODEL_INFERENCE_META_FILENAME} already exists, skipping download"; \
+		echo "model file ${MODEL_PB} already exists, skipping download"; \
 	else \
-		echo "Downloading ${MODEL_INFERENCE_META_FILENAME} file"; \
-		${GET_MODEL_META}; \
-		if [ -e ${MODEL_INFERENCE_META_FILENAME} ] ; \
+		echo "Downloading ${MODEL_INFERENCE_PB} file" ; \
+		${GET_MODEL_PB} ; \
+		if [ -e ${MODEL_PB} ] ; \
 		then \
-			echo "download ${MODEL_INFERENCE_META_FILENAME} done."; \
+			echo "download ${MODEL_INFERENCE_PB} done. Downloaded to /tensorflow_model."; \
 		else \
-			echo "***\nError - Could not download ${MODEL_INFERENCE_META_FILENAME}. Check network and proxy settings \n***\n"; \
-			exit 1; \
-		fi ; \
-	fi
-	@if [ -e ${MODEL_INFERENCE_INDEX_FILENAME} ] ; \
-	then \
-		echo "model file ${MODEL_INFERENCE_INDEX_FILENAME} already exists, skipping download"; \
-	else \
-		echo "Downloading ${MODEL_INFERENCE_INDEX_FILENAME} file"; \
-		${GET_MODEL_INDEX}; \
-		if [ -e ${MODEL_INFERENCE_INDEX_FILENAME} ] ; \
-		then \
-			echo "download ${MODEL_INFERENCE_INDEX_FILENAME} done."; \
-		else \
-			echo "***\nError - Could not download ${MODEL_INFERENCE_INDEX_FILENAME}. Check network and proxy settings \n***\n"; \
+			echo "***\nError - Could not download ${MODEL_INFERENCE_PB}. Check network and proxy settings \n***\n"; \
 			exit 1; \
 		fi ; \
 	fi
@@ -147,18 +136,28 @@ train:
 
 .PHONY: compile_model
 compile_model: get_model
-	@echo $(YELLOW)"\nMnist: Compiling model to IR..."$(NOCOLOR)
-	@if [ -e ${GRAPH_FILENAME_BASE}.xml ] ; \
+	@echo $(YELLOW)"\nSSD Inception V2: Compiling model to IR..."$(NOCOLOR)
+	@if [ -e ${GRAPH_FILENAME_BASE_IN_DIR_FP32} ] ; \
 	then \
-		echo "compiled model file already exists, skipping compile."; \
+		echo "compiled FP32 model file already exists, skipping compile."; \
 	else \
-		${NCCOMPILE} --data_type=FP16 --input_meta_graph=${MODEL_INFERENCE_META_FILENAME} --input_shape=${INPUT_SHAPE} || (echo $(RED)"Make sure to set the OpenVINO environment variables using the "$(YELLOW)"setupvars.sh"$(RED)" script found in <your OpenVINO install location>/bin/ folder."$(NOCOLOR);  exit 1;); \
+		echo "Compiling FP32 model..."; \
+		mkdir ssd_inception_v2_mo_fp32 ; \
+		${NCCOMPILE} --data_type=FP32 --reverse_input_channels ${MO_INPUT_GRAPH_ARG} ${MO_INPUT_PIPELINE} ${MO_INPUT_CUSTOM_OPS} ${MO_OUTPUT_DIR_FP32} || (echo $(RED)"Make sure to set the OpenVINO environment variables using the "$(YELLOW)"setupvars.sh"$(RED)" script found in <your OpenVINO install location>/bin/ folder."$(NOCOLOR);  exit 1;); \
+	fi
+	@if [ -e ${GRAPH_FILENAME_BASE_IN_DIR_FP16} ] ; \
+	then \
+		echo "compiled FP16 model file already exists, skipping compile."; \
+	else \
+		echo "Compiling FP16 model..."; \
+		mkdir ssd_inception_v2_mo_fp16 ; \
+		${NCCOMPILE} --data_type=FP16 --reverse_input_channels ${MO_INPUT_GRAPH_ARG} ${MO_INPUT_PIPELINE} ${MO_INPUT_CUSTOM_OPS} ${MO_OUTPUT_DIR_FP16} || (echo $(RED)"Make sure to set the OpenVINO environment variables using the "$(YELLOW)"setupvars.sh"$(RED)" script found in <your OpenVINO install location>/bin/ folder."$(NOCOLOR);  exit 1;); \
 	fi
 
 
 .PHONY: install-reqs
 install-reqs:
-	@echo $(YELLOW)"\nMnist: Checking application requirements...\n"$(NOCOLOR)
+	@echo $(YELLOW)"\nSSD Inception V2: Checking application requirements...\n"$(NOCOLOR)
 	@echo "No requirements needed."
 
 
@@ -168,7 +167,7 @@ run: run_py
 
 .PHONY: run_py
 run_py: install-reqs deps data compile_model
-	@echo $(YELLOW) "\nMnist: Running Python sample..." $(NOCOLOR)
+	@echo $(YELLOW) "\nSSD Inception V2: Running Python sample..." $(NOCOLOR)
 	python3 $(RUN_PY_RELATIVE_DIR) --ir=${MODEL_RELATIVE_DIR}/${GRAPH_FILENAME_BASE}.xml --image=${TEST_IMAGE_RELATIVE_DIR}/${TEST_IMAGE_FILENAME} --labels=categories.txt
 
 
@@ -187,18 +186,7 @@ help:
 	@echo $(YELLOW)"  make train " $(NOCOLOR) "- Train a mnist model.";
 
 clean: clean
-	@echo $(YELLOW)"\nMnist: Cleaning up files..."$(NOCOLOR)
-	rm -f ${GRAPH_FILENAME_BASE}.bin
-	rm -f ${GRAPH_FILENAME_BASE}.mapping.json
-	rm -f ${GRAPH_FILENAME_BASE}.mapping
-	rm -f ${GRAPH_FILENAME_BASE}.xml
-	rm -f ${MODEL_INFERENCE_META_FILENAME}
-	rm -f ${MODEL_INFERENCE_INDEX_FILENAME}
-	rm -f ${MODEL_INFERENCE_DATA_FILENAME}
-	rm -f ${MNIST_NCS_FILENAME}
-	rm -f ${MNIST_INFERENCE_FILENAME}
-	rm -f ${NETWORK_SCRIPT_FILENAME}
-	rm -f ${MODEL_DATA_FILENAME}
-	rm -f ${MODEL_INDEX_FILENAME}
-	rm -f ${MODEL_META_FILENAME}
-	rm -f checkpoint
+	@echo $(YELLOW)"\nSSD Inception V2: Cleaning up files..."$(NOCOLOR)
+	rm -rf ${GRAPH_DIR_FP32}
+	rm -rf ${GRAPH_DIR_FP16}
+	rm -rf ${MODEL_DIR}
